name: Web E2E Testes

on: 
  workflow_dispatch:

jobs: 
  e2e-testes:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v4
      
      - name: Node version
        run: node --version
        
      - name: Installing dependencies
        run: npm install
        
      - name: Running the tests
        run: npx cypress run
        
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: Reports
          path: |
            cypress/reports
            cypress/screenshots
            cypress/videos
      
